name: Secrets and Composite Action

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Printing secret directly using env
        env:
          GREETING_MESSAGE: ${{ secrets.GREETING_MESSAGE }}
        run: |
              echo "The secret greeting message is: $GREETING_MESSAGE"

      - name: Use composite action
        uses: ./.github/actions/print-info
        with:
          greeting: ${{ secrets.GREETING_MESSAGE }}
          farewell: Repo 2 tasks almost finished.